ci(AXD-47): fix backup step, not being required

diff --git a/.github/workflows/sanity.yml b/.github/workflows/sanity.yml
--- a/.github/workflows/sanity.yml
+++ b/.github/workflows/sanity.yml
@@ -90,7 +90,22 @@ jobs:
         run: yarn install --immutable
       - name: Build for deploy
         run: yarn build
+      - name: Is Backup Required on LionDev Cloud
+        uses: appleboy/ssh-action@v1.0.0
+        id: backup-required
+        env:
+          DEPLOY_PATH: ${{ vars.SANITY_DEPLOY_PATH }}
+        with:
+          host: ${{ secrets.DEPLOY_SSH_HOST }}
+          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
+          key: ${{ secrets.DEPLOY_SSH_KEY }}
+          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
+          port: ${{ secrets.DEPLOY_SSH_PORT }}
+          envs: DEPLOY_PATH
+          script: |
+            echo "BACKUP_REQUIRED=[ -d ~/$DEPLOY_PATH/* ] && echo 'true' || echo 'false'" >> $GITHUB_OUTPUT
       - name: Delete and Backup Previous deployment to Alpha LionDev Cloud
+        if: steps.backup-required.outputs.BACKUP_REQUIRED == 'true'
         id: backup-and-delete
         uses: appleboy/ssh-action@v1.0.0
         env:
