ci(AXD-47): fix backup required step

diff --git a/.github/workflows/sanity.yml b/.github/workflows/sanity.yml
--- a/.github/workflows/sanity.yml
+++ b/.github/workflows/sanity.yml
@@ -103,7 +103,7 @@ jobs:
           port: ${{ secrets.DEPLOY_SSH_PORT }}
           envs: DEPLOY_PATH
           script: |
-            echo "BACKUP_REQUIRED=[ -d ~/$DEPLOY_PATH/* ] && echo 'true' || echo 'false'" >> $GITHUB_OUTPUT
+            echo "BACKUP_REQUIRED=$([ -d ~/$DEPLOY_PATH/* ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
       - name: Delete and Backup Previous deployment to Alpha LionDev Cloud
         if: steps.backup-required.outputs.BACKUP_REQUIRED == 'true'
         id: backup-and-delete
